version: "3.8"
services:
  product-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: product-api:latest
    ports:
      - "8081:8081"
    environment:
      JAVA_OPTS: "-Xms256m -Xmx512m"
    depends_on:
      - kafka
    restart: unless-stopped
    networks:
      - shop-net

networks:
  stock-net:
    driver: bridge